// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VLXD_API.Models;

#nullable disable

namespace VLXD_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513111019_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VLXD_API.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("don_gia");

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("don_vi_tinh");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int")
                        .HasColumnName("ma_don_hang");

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("ma_san_pham");

                    b.Property<decimal>("SoLuong")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("so_luong");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("thanh_tien")
                        .HasComputedColumnSql("`so_luong` * `don_gia`", true);

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaDonHang" }, "fk_ctdh_dh");

                    b.HasIndex(new[] { "MaSanPham" }, "fk_ctdh_sp");

                    b.ToTable("chi_tiet_don_hang");
                });

            modelBuilder.Entity("VLXD_API.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GiaNhap")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_nhap");

                    b.Property<bool?>("LoaiNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("loai_nhap");

                    b.Property<int?>("MaPhieuNhap")
                        .HasColumnType("int")
                        .HasColumnName("ma_phieu_nhap");

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("ma_san_pham");

                    b.Property<decimal>("SoLuong")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("so_luong");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("thanh_tien")
                        .HasComputedColumnSql("`so_luong` * `gia_nhap`", true);

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaPhieuNhap" }, "fk_ctpn_pn");

                    b.HasIndex(new[] { "MaSanPham" }, "fk_ctpn_sp");

                    b.ToTable("chi_tiet_phieu_nhap");
                });

            modelBuilder.Entity("VLXD_API.Models.CongNoKhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int")
                        .HasColumnName("ma_don_hang");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int")
                        .HasColumnName("ma_khach_hang");

                    b.Property<DateTime?>("NgayPhatSinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_phat_sinh")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("SoTienNo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("so_tien_no");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('dang_no','hoan_tat')")
                        .HasColumnName("trang_thai")
                        .HasDefaultValueSql("'dang_no'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaKhachHang" }, "fk_cnkh_kh");

                    b.ToTable("cong_no_khach_hang");
                });

            modelBuilder.Entity("VLXD_API.Models.CongNoNcc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaNcc")
                        .HasColumnType("int")
                        .HasColumnName("ma_ncc");

                    b.Property<int?>("MaPhieuNhap")
                        .HasColumnType("int")
                        .HasColumnName("ma_phieu_nhap");

                    b.Property<DateTime?>("NgayPhatSinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_phat_sinh")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("SoTienNo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("so_tien_no");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('dang_no','hoan_tat')")
                        .HasColumnName("trang_thai")
                        .HasDefaultValueSql("'dang_no'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaNcc" }, "fk_cnncc_ncc");

                    b.ToTable("cong_no_ncc");
                });

            modelBuilder.Entity("VLXD_API.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_danh_muc");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ten_danh_muc");

                    b.HasKey("MaDanhMuc")
                        .HasName("PRIMARY");

                    b.ToTable("danh_muc");
                });

            modelBuilder.Entity("VLXD_API.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_don_hang");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<bool?>("HinhThuc")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("hinh_thuc");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int")
                        .HasColumnName("ma_khach_hang");

                    b.Property<int?>("MaNguoiTao")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_tao");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("SoTienTra")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("so_tien_tra");

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tong_tien")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<string>("TrangThaiThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('chua_thanh_toan','thanh_toan_mot_phan','da_thanh_toan')")
                        .HasColumnName("trang_thai_thanh_toan")
                        .HasDefaultValueSql("'chua_thanh_toan'");

                    b.HasKey("MaDonHang")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaKhachHang" }, "fk_dh_kh");

                    b.HasIndex(new[] { "MaNguoiTao" }, "fk_dh_nv");

                    b.ToTable("don_hang");
                });

            modelBuilder.Entity("VLXD_API.Models.DonViQuyDoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("GiaBanTheoDv")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_ban_theo_dv");

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("ma_san_pham");

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ten_don_vi");

                    b.Property<decimal>("TyLeQuyDoi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ty_le_quy_doi");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaSanPham" }, "fk_quydoi_sp");

                    b.ToTable("don_vi_quy_doi");
                });

            modelBuilder.Entity("VLXD_API.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_khach_hang");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("dia_chi");

                    b.Property<decimal?>("HanMucNo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("han_muc_no")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("so_dien_thoai");

                    b.HasKey("MaKhachHang")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SoDienThoai" }, "so_dien_thoai")
                        .IsUnique();

                    b.ToTable("khach_hang");
                });

            modelBuilder.Entity("VLXD_API.Models.Kho", b =>
                {
                    b.Property<int>("MaKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_kho");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaKho"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("SoDienThoaiKho")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("so_dien_thoai_kho");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ten_kho");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("trang_thai")
                        .HasDefaultValueSql("'1'");

                    b.HasKey("MaKho")
                        .HasName("PRIMARY");

                    b.ToTable("kho");
                });

            modelBuilder.Entity("VLXD_API.Models.LichSuThanhToan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("GhiChu"), "utf8mb4");

                    b.Property<bool>("IsNhaCungCap")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("PhuongThucThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasComment("0: tien_mat, 1: chuyen_khoan");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("conNoID")
                        .HasColumnType("int")
                        .HasColumnName("conNoID");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("lichsuthanhtoan", (string)null);
                });

            modelBuilder.Entity("VLXD_API.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mat_khau_hash");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ten_dang_nhap");

                    b.Property<string>("VaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('admin','ban_hang','thu_kho','ke_toán')")
                        .HasColumnName("vai_tro")
                        .HasDefaultValueSql("'ban_hang'");

                    b.HasKey("MaNguoiDung")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TenDangNhap" }, "ten_dang_nhap")
                        .IsUnique();

                    b.ToTable("nguoi_dung");
                });

            modelBuilder.Entity("VLXD_API.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNcc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_ncc");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaNcc"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("text")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TenNcc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_ncc");

                    b.HasKey("MaNcc")
                        .HasName("PRIMARY");

                    b.ToTable("nha_cung_cap");
                });

            modelBuilder.Entity("VLXD_API.Models.PhieuNhapKho", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_phieu_nhap");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaPhieuNhap"));

                    b.Property<decimal?>("DaThanhToanNcc")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("da_thanh_toan_ncc")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<int?>("MaKhoNhap")
                        .HasColumnType("int")
                        .HasColumnName("ma_kho_nhap");

                    b.Property<int?>("MaNcc")
                        .HasColumnType("int")
                        .HasColumnName("ma_ncc");

                    b.Property<int?>("MaNguoiLap")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_lap");

                    b.Property<DateTime?>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_nhap")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("TongTienNhap")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tong_tien_nhap")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('cho_nhap','da_nhap_kho','da_huy')")
                        .HasColumnName("trang_thai")
                        .HasDefaultValueSql("'cho_nhap'");

                    b.HasKey("MaPhieuNhap")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaKhoNhap" }, "fk_pnk_kho");

                    b.HasIndex(new[] { "MaNcc" }, "fk_pnk_ncc");

                    b.HasIndex(new[] { "MaNguoiLap" }, "fk_pnk_nv");

                    b.ToTable("phieu_nhap_kho");
                });

            modelBuilder.Entity("VLXD_API.Models.PhieuXuatKho", b =>
                {
                    b.Property<int>("MaPhieuXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_phieu_xuat");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaPhieuXuat"));

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int")
                        .HasColumnName("ma_don_hang");

                    b.Property<int?>("MaKhoXuat")
                        .HasColumnType("int")
                        .HasColumnName("ma_kho_xuat");

                    b.Property<int?>("MaNguoiXuat")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_xuat");

                    b.Property<DateTime?>("NgayXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_xuat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TrangThaiXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('cho_xuat','da_xuat_kho')")
                        .HasColumnName("trang_thai_xuat")
                        .HasDefaultValueSql("'cho_xuat'");

                    b.HasKey("MaPhieuXuat")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaDonHang" }, "fk_pxk_dh");

                    b.HasIndex(new[] { "MaKhoXuat" }, "fk_pxk_kho");

                    b.ToTable("phieu_xuat_kho");
                });

            modelBuilder.Entity("VLXD_API.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_san_pham");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<string>("DonViChinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("don_vi_chinh");

                    b.Property<decimal?>("GiaBanLe")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_ban_le")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<decimal?>("GiaNhapGanNhat")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_nhap_gan_nhat")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<decimal?>("GiaSauThue")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_sau_thue")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int")
                        .HasColumnName("ma_danh_muc");

                    b.Property<int?>("MaNccMacDinh")
                        .HasColumnType("int")
                        .HasColumnName("ma_ncc_mac_dinh");

                    b.Property<string>("MaSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ma_sku");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("so_luong");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_san_pham");

                    b.Property<decimal?>("Thue")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("thue")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<int?>("TonKhoToiDa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ton_kho_toi_da")
                        .HasDefaultValueSql("'500'");

                    b.Property<int?>("TonKhoToiThieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ton_kho_toi_thieu")
                        .HasDefaultValueSql("'10'");

                    b.HasKey("MaSanPham")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaDanhMuc" }, "fk_sp_danhmuc");

                    b.HasIndex(new[] { "MaNccMacDinh" }, "fk_sp_ncc");

                    b.HasIndex(new[] { "MaSku" }, "ma_sku")
                        .IsUnique();

                    b.ToTable("san_pham");
                });

            modelBuilder.Entity("VLXD_API.Models.TheKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LoaiGiaoDich")
                        .IsRequired()
                        .HasColumnType("enum('NHAP_HANG','XUAT_HANG','KIEM_KE','TRA_HANG')")
                        .HasColumnName("loai_giao_dich");

                    b.Property<string>("MaChungTuLienQuan")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ma_chung_tu_lien_quan");

                    b.Property<int?>("MaKho")
                        .HasColumnType("int")
                        .HasColumnName("ma_kho");

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("ma_san_pham");

                    b.Property<DateTime?>("NgayThayDoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_thay_doi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("SoLuongThayDoi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("so_luong_thay_doi");

                    b.Property<decimal>("SoLuongTonSauKhiThayDoi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("so_luong_ton_sau_khi_thay_doi");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaKho" }, "fk_tk_kho");

                    b.HasIndex(new[] { "MaSanPham" }, "fk_tk_sp");

                    b.ToTable("the_kho");
                });

            modelBuilder.Entity("VLXD_API.Models.TonKhoChiTiet", b =>
                {
                    b.Property<int>("MaKho")
                        .HasColumnType("int")
                        .HasColumnName("ma_kho");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("ma_san_pham");

                    b.Property<decimal?>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("so_luong_ton")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<string>("ViTriCuThe")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("vi_tri_cu_the");

                    b.HasKey("MaKho", "MaSanPham")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "MaSanPham" }, "fk_ton_sp");

                    b.ToTable("ton_kho_chi_tiet");
                });

            modelBuilder.Entity("VLXD_API.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("VLXD_API.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .HasConstraintName("fk_ctdh_dh");

                    b.HasOne("VLXD_API.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("fk_ctdh_sp");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("VLXD_API.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("VLXD_API.Models.PhieuNhapKho", "MaPhieuNhapNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .HasConstraintName("fk_ctpn_pn");

                    b.HasOne("VLXD_API.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("fk_ctpn_sp");

                    b.Navigation("MaPhieuNhapNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("VLXD_API.Models.CongNoKhachHang", b =>
                {
                    b.HasOne("VLXD_API.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("CongNoKhachHangs")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("fk_cnkh_kh");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("VLXD_API.Models.CongNoNcc", b =>
                {
                    b.HasOne("VLXD_API.Models.NhaCungCap", "MaNccNavigation")
                        .WithMany("CongNoNccs")
                        .HasForeignKey("MaNcc")
                        .HasConstraintName("fk_cnncc_ncc");

                    b.Navigation("MaNccNavigation");
                });

            modelBuilder.Entity("VLXD_API.Models.DonHang", b =>
                {
                    b.HasOne("VLXD_API.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("fk_dh_kh");

                    b.HasOne("VLXD_API.Models.NguoiDung", "MaNguoiTaoNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNguoiTao")
                        .HasConstraintName("fk_dh_nv");

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaNguoiTaoNavigation");
                });

            modelBuilder.Entity("VLXD_API.Models.DonViQuyDoi", b =>
                {
                    b.HasOne("VLXD_API.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("DonViQuyDois")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("fk_quydoi_sp");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("VLXD_API.Models.PhieuNhapKho", b =>
                {
                    b.HasOne("VLXD_API.Models.Kho", "MaKhoNhapNavigation")
                        .WithMany("PhieuNhapKhos")
                        .HasForeignKey("MaKhoNhap")
                        .HasConstraintName("fk_pnk_kho");

                    b.HasOne("VLXD_API.Models.NhaCungCap", "MaNccNavigation")
                        .WithMany("PhieuNhapKhos")
                        .HasForeignKey("MaNcc")
                        .HasConstraintName("fk_pnk_ncc");

                    b.HasOne("VLXD_API.Models.NguoiDung", "MaNguoiLapNavigation")
                        .WithMany("PhieuNhapKhos")
                        .HasForeignKey("MaNguoiLap")
                        .HasConstraintName("fk_pnk_nv");

                    b.Navigation("MaKhoNhapNavigation");

                    b.Navigation("MaNccNavigation");

                    b.Navigation("MaNguoiLapNavigation");
                });

            modelBuilder.Entity("VLXD_API.Models.PhieuXuatKho", b =>
                {
                    b.HasOne("VLXD_API.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("PhieuXuatKhos")
                        .HasForeignKey("MaDonHang")
                        .HasConstraintName("fk_pxk_dh");

                    b.HasOne("VLXD_API.Models.Kho", "MaKhoXuatNavigation")
                        .WithMany("PhieuXuatKhos")
                        .HasForeignKey("MaKhoXuat")
                        .HasConstraintName("fk_pxk_kho");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaKhoXuatNavigation");
                });

            modelBuilder.Entity("VLXD_API.Models.SanPham", b =>
                {
                    b.HasOne("VLXD_API.Models.DanhMuc", "MaDanhMucNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDanhMuc")
                        .HasConstraintName("fk_sp_danhmuc");

                    b.HasOne("VLXD_API.Models.NhaCungCap", "MaNccMacDinhNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaNccMacDinh")
                        .HasConstraintName("fk_sp_ncc");

                    b.Navigation("MaDanhMucNavigation");

                    b.Navigation("MaNccMacDinhNavigation");
                });

            modelBuilder.Entity("VLXD_API.Models.TheKho", b =>
                {
                    b.HasOne("VLXD_API.Models.Kho", "MaKhoNavigation")
                        .WithMany("TheKhos")
                        .HasForeignKey("MaKho")
                        .HasConstraintName("fk_tk_kho");

                    b.HasOne("VLXD_API.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("TheKhos")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("fk_tk_sp");

                    b.Navigation("MaKhoNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("VLXD_API.Models.TonKhoChiTiet", b =>
                {
                    b.HasOne("VLXD_API.Models.Kho", "MaKhoNavigation")
                        .WithMany("TonKhoChiTiets")
                        .HasForeignKey("MaKho")
                        .IsRequired()
                        .HasConstraintName("fk_ton_kho");

                    b.HasOne("VLXD_API.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("TonKhoChiTiets")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("fk_ton_sp");

                    b.Navigation("MaKhoNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("VLXD_API.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("VLXD_API.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("PhieuXuatKhos");
                });

            modelBuilder.Entity("VLXD_API.Models.KhachHang", b =>
                {
                    b.Navigation("CongNoKhachHangs");

                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("VLXD_API.Models.Kho", b =>
                {
                    b.Navigation("PhieuNhapKhos");

                    b.Navigation("PhieuXuatKhos");

                    b.Navigation("TheKhos");

                    b.Navigation("TonKhoChiTiets");
                });

            modelBuilder.Entity("VLXD_API.Models.NguoiDung", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("PhieuNhapKhos");
                });

            modelBuilder.Entity("VLXD_API.Models.NhaCungCap", b =>
                {
                    b.Navigation("CongNoNccs");

                    b.Navigation("PhieuNhapKhos");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("VLXD_API.Models.PhieuNhapKho", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("VLXD_API.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("DonViQuyDois");

                    b.Navigation("TheKhos");

                    b.Navigation("TonKhoChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
